language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

jdk:
  - oraclejdk8

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

install:
    - sdkmanager --list || true
    - echo yes | sdkmanager "tools"
    - echo yes | sdkmanager "platforms;android-26"
    - echo yes | sdkmanager "extras;google;m2repository"
    - echo yes | sdkmanager "extras;android;m2repository"
    - sdkmanager --list || true

script:
    - ./gradlew clean build

notifications:
    email:
        - tech@hikyson.cn

after_success:
    - echo check should deploy?
    - test tag IS present && test branch = master && echo deploying to jcenter... && ./gradlew clean build bintrayUpload -PbintrayUser=kyson -PbintrayKey=$BINTRAY_KEY -PdryRun=false && echo deployed to jcenter.